"""Readable FCC event-production workflow."""

from __future__ import annotations

import gzip
import json
import os
import secrets
import shutil
import subprocess
import sys
import textwrap
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from lhapdf import inspect_lhapdf, prepare_lhapdf
from parsers import (
    load_manifest,
    matching_description,
    parse_lhe,
    parse_madgraph_card,
    parse_podio_event_count,
    patch_delphes_seed,
    render_template,
)


@dataclass(frozen=True)
class WorkflowOptions:
    config_file: Path
    prepare: bool
    dry_run: bool
    confirm: bool
    overwrite: bool
    keep_lhe: bool
    keep_work: bool
    lhapdf_directory: Path


def run_fcc_workflow(options: WorkflowOptions) -> int:
    """Run the complete MG5 -> Pythia8 -> Delphes -> EDM4hep workflow."""

    # 1. Load the manifest and resolve the input cards.
    config_file = options.config_file.expanduser().resolve()
    require_file(config_file, "Production configuration")

    config_directory = config_file.parent
    manifest = load_manifest(config_file)
    cards = resolve_cards(manifest, config_directory)

    # 2. Read the production definition from the single MadGraph card.
    madgraph_information = parse_madgraph_card(cards["madgraph"])

    layout = build_output_layout(
        config_directory,
        madgraph_information["output_directory"],
        madgraph_information["sample_name"],
    )

    # 3. Check the Key4hep commands required by the workflow.
    executables = {
        "mg5_aMC": require_executable("mg5_aMC"),
        "DelphesPythia8_EDM4HEP": require_executable(
            "DelphesPythia8_EDM4HEP"
        ),
        "podio-dump": require_executable("podio-dump"),
    }

    environment = dict(os.environ)

    # 4. Inspect the PDF without modifying the environment.
    pdf_information = inspect_lhapdf(
        madgraph_information["lhaid"],
        options.lhapdf_directory,
        environment,
    )

    # 5. Show the resolved production before taking any action.
    print_production_summary(
        cards=cards,
        madgraph_information=madgraph_information,
        pdf_information=pdf_information,
        root_file=layout["root_file"],
    )

    if options.dry_run:
        print("\nDry run completed. No files were generated.")
        return 0

    request_confirmation(options.confirm)

    # 6. Prepare the writable LHAPDF environment when needed.
    pdf_information = prepare_lhapdf(
        madgraph_information["lhaid"],
        options.lhapdf_directory,
        environment,
        install=True,
    )

    if options.prepare:
        if pdf_information is None:
            print("\nEnvironment preparation completed. No PDF was requested.")
        else:
            print(
                "\nEnvironment preparation completed: "
                f"{pdf_information['name']}"
            )

        return 0

    # 7. Protect existing outputs and previous MadGraph work.
    protect_existing_paths(layout, options)
    print("\nStarting event generation...")

    # 8. Run the complete MadGraph card.
    run_id = create_run_id()
    log_directory = layout["log_base"] / run_id
    log_directory.mkdir(parents=True)

    shutil.copy2(config_file, log_directory / "config.yaml")
    shutil.copy2(
        cards["madgraph"],
        log_directory / cards["madgraph"].name,
    )

    success = False
    temporary_root = (
        layout["output_directory"]
        / f".{layout['sample_name']}.{run_id}.tmp.root"
    )

    try:
        print("\n[1/3] Running MadGraph5...")

        run_logged_command(
            command=[
                executables["mg5_aMC"],
                str(cards["madgraph"]),
            ],
            log_file=log_directory / "madgraph.log",
            working_directory=config_directory,
            environment=environment,
        )

        # 9. Locate and inspect the LHE generated by MadGraph.
        lhe_source = locate_lhe(layout["process_directory"])
        lhe_file = (
            layout["process_directory"]
            / "Events"
            / "fcc_runner_events.lhe"
        )

        unpack_lhe(
            source=lhe_source,
            destination=lhe_file,
        )

        lhe_information = parse_lhe(lhe_file)

        if lhe_information["events"] <= 0:
            raise RuntimeError(
                f"The generated LHE file contains no events: {lhe_file}"
            )

        # 10. Prepare the Pythia and Delphes runtime cards.
        seeds = create_runtime_seeds(madgraph_information["iseed"])

        pythia_content = render_template(
            cards["pythia"],
            {
                "LHE_FILE": lhe_file,
                "LHE_EVENTS": lhe_information["events"],
                "PYTHIA_SEED": seeds["pythia"],
            },
        )

        runtime_pythia_card = log_directory / cards["pythia"].name
        runtime_pythia_card.write_text(
            pythia_content,
            encoding="utf-8",
        )

        delphes_content = patch_delphes_seed(
            cards["delphes"],
            seeds["delphes"],
        )

        runtime_delphes_card = log_directory / "delphes_runtime.tcl"
        runtime_delphes_card.write_text(
            delphes_content,
            encoding="utf-8",
        )

        # 11. Run Pythia8 and Delphes through the Key4hep executable.
        print("\n[2/3] Running Pythia8 and Delphes...")

        layout["output_directory"].mkdir(
            parents=True,
            exist_ok=True,
        )

        run_logged_command(
            command=[
                executables["DelphesPythia8_EDM4HEP"],
                str(runtime_delphes_card),
                str(cards["edm4hep"]),
                str(runtime_pythia_card),
                str(temporary_root),
            ],
            log_file=log_directory / "pythia_delphes.log",
            working_directory=config_directory,
            environment=environment,
        )

        # 12. Validate the EDM4hep output.
        print("\n[3/3] Validating the EDM4hep output...")

        output_events = validate_edm4hep_output(
            root_file=temporary_root,
            podio_dump=executables["podio-dump"],
            log_file=log_directory / "validation.log",
            environment=environment,
        )

        if output_events <= 0:
            raise RuntimeError("The EDM4hep output contains no events.")

        # 13. Preserve the generated production cards and metadata.
        preserve_madgraph_metadata(
            process_directory=layout["process_directory"],
            lhe_source=lhe_source,
            log_directory=log_directory,
        )

        if options.keep_lhe:
            save_lhe_output(
                lhe_file=lhe_file,
                output_file=layout["lhe_file"],
            )

        metadata = build_metadata(
            run_id=run_id,
            cards=cards,
            executables=executables,
            madgraph_information=madgraph_information,
            lhe_information=lhe_information,
            output_events=output_events,
            pdf_information=pdf_information,
            seeds=seeds,
            root_file=layout["root_file"],
            log_directory=log_directory,
        )

        # 14. Replace the final output only after successful validation.
        os.replace(temporary_root, layout["root_file"])

        layout["metadata_file"].write_text(
            json.dumps(
                metadata,
                indent=2,
                ensure_ascii=False,
            )
            + "\n",
            encoding="utf-8",
        )

        success = True

        print("\nProduction completed successfully.")
        print(f"EDM4hep output : {layout['root_file']}")
        print(f"Metadata       : {layout['metadata_file']}")
        print(f"Logs           : {log_directory}")

        return 0

    finally:
        temporary_root.unlink(missing_ok=True)

        if success and not options.keep_work:
            remove_process_directory(
                layout["process_directory"],
                config_directory,
            )

        if not success and layout["process_directory"].exists():
            print(
                "\nThe failed MadGraph process directory was preserved:",
                file=sys.stderr,
            )
            print(
                f"  {layout['process_directory']}",
                file=sys.stderr,
            )


def resolve_cards(
    manifest: dict[str, str],
    config_directory: Path,
) -> dict[str, Path]:
    cards = {
        "madgraph": resolve_path(
            manifest["madgraph_card"],
            config_directory,
        ),
        "pythia": resolve_path(
            manifest["pythia_card"],
            config_directory,
        ),
        "delphes": resolve_path(
            manifest["delphes_card"],
            config_directory,
        ),
        "edm4hep": resolve_path(
            manifest["edm4hep_card"],
            config_directory,
        ),
    }

    for name, path in cards.items():
        require_file(path, f"{name} card")

    return cards


def resolve_path(
    value: str,
    base_directory: Path,
) -> Path:
    expanded = os.path.expandvars(os.path.expanduser(value))
    path = Path(expanded)

    if not path.is_absolute():
        path = base_directory / path

    return path.resolve()


def build_output_layout(
    config_directory: Path,
    madgraph_output: str,
    sample_name: str,
) -> dict[str, Any]:
    process_directory = (
        config_directory
        / madgraph_output
    ).resolve()

    try:
        relative_process = process_directory.relative_to(
            config_directory
        )
    except ValueError as error:
        raise RuntimeError(
            "The MadGraph output must remain inside the configuration directory."
        ) from error

    if not relative_process.parts:
        raise RuntimeError(
            "The MadGraph output cannot be the configuration directory."
        )

    output_directory = (
        config_directory
        / "outputs"
    ).resolve()

    return {
        "sample_name": sample_name,
        "process_directory": process_directory,
        "output_directory": output_directory,
        "root_file": output_directory / f"{sample_name}.root",
        "metadata_file": (
            output_directory
            / f"{sample_name}.metadata.json"
        ),
        "lhe_file": output_directory / f"{sample_name}.lhe.gz",
        "log_base": (
            config_directory
            / "logs"
            / sample_name
        ).resolve(),
    }


def require_file(
    path: Path,
    description: str,
) -> None:
    if not path.is_file():
        raise RuntimeError(f"{description} was not found: {path}")


def require_executable(name: str) -> str:
    executable = shutil.which(name)

    if executable is None:
        raise RuntimeError(
            f"'{name}' was not found. "
            "Load the Key4hep environment before running FCC Event Runner."
        )

    return str(Path(executable).resolve())


def print_production_summary(
    cards: dict[str, Path],
    madgraph_information: dict[str, Any],
    pdf_information: dict[str, Any] | None,
    root_file: Path,
) -> None:
    if pdf_information is None:
        pdf_value = "Not requested"
    elif pdf_information["name"]:
        status = (
            "installed"
            if pdf_information["installed"]
            else "not installed"
        )
        pdf_value = (
            f"{pdf_information['lhaid']} "
            f"({pdf_information['name']}, {status})"
        )
    else:
        pdf_value = str(pdf_information["lhaid"])

    rows = [
        ("MadGraph card", str(cards["madgraph"])),
        ("Pythia card", str(cards["pythia"])),
        ("Delphes card", str(cards["delphes"])),
        (
            "MG5 output",
            madgraph_information["output_directory"],
        ),
        (
            "Events",
            display_value(madgraph_information["nevents"]),
        ),
        (
            "Beam 1 energy",
            display_energy(madgraph_information["ebeam1"]),
        ),
        (
            "Beam 2 energy",
            display_energy(madgraph_information["ebeam2"]),
        ),
        ("LHAPDF", pdf_value),
        (
            "Jet matching",
            matching_description(madgraph_information),
        ),
        ("Final output", str(root_file)),
    ]

    print_table(rows)


def print_table(rows: list[tuple[str, str]]) -> None:
    label_width = max(
        len("Production setting"),
        *(len(label) for label, _ in rows),
    )
    value_width = 68

    border = (
        "+"
        + "-" * (label_width + 2)
        + "+"
        + "-" * (value_width + 2)
        + "+"
    )

    print(border)
    print(
        f"| {'Production setting':<{label_width}} "
        f"| {'Value':<{value_width}} |"
    )
    print(border)

    for label, value in rows:
        wrapped_lines = textwrap.wrap(
            str(value),
            width=value_width,
            break_long_words=True,
            break_on_hyphens=False,
        ) or [""]

        for line_number, line in enumerate(wrapped_lines):
            displayed_label = label if line_number == 0 else ""

            print(
                f"| {displayed_label:<{label_width}} "
                f"| {line:<{value_width}} |"
            )

    print(border)


def display_value(value: Any) -> str:
    return "Not specified" if value is None else str(value)


def display_energy(value: float | None) -> str:
    if value is None:
        return "Not specified"

    return f"{value:g} GeV"


def request_confirmation(confirm: bool) -> None:
    if not confirm:
        return

    if not sys.stdin.isatty():
        raise RuntimeError(
            "--confirm requires an interactive terminal."
        )

    input("\nPress Enter to start or Ctrl+C to cancel: ")


def protect_existing_paths(
    layout: dict[str, Any],
    options: WorkflowOptions,
) -> None:
    root_file = layout["root_file"]
    process_directory = layout["process_directory"]

    if root_file.exists() and not options.overwrite:
        raise RuntimeError(
            f"Output already exists: {root_file}\n"
            "Use --overwrite to replace it after successful validation."
        )

    if process_directory.exists():
        raise RuntimeError(
            f"MadGraph output directory already exists: {process_directory}\n"
            "Remove or move it before starting a new production."
        )


def run_logged_command(
    command: list[str],
    log_file: Path,
    working_directory: Path,
    environment: dict[str, str],
) -> None:
    print(f"Running: {' '.join(command)}")

    with log_file.open(
        "w",
        encoding="utf-8",
    ) as log:
        process = subprocess.Popen(
            command,
            cwd=working_directory,
            env=environment,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )

        assert process.stdout is not None

        for line in process.stdout:
            print(line, end="")
            log.write(line)

        return_code = process.wait()

    if return_code != 0:
        raise RuntimeError(
            f"Command returned {return_code}. See: {log_file}"
        )


def locate_lhe(
    process_directory: Path,
) -> Path:
    events_directory = process_directory / "Events"

    if not events_directory.is_dir():
        raise RuntimeError(
            f"MadGraph Events directory was not found: {events_directory}"
        )

    names = [
        "unweighted_events.lhe.gz",
        "unweighted_events.lhe",
        "events.lhe.gz",
        "events.lhe",
    ]

    found: list[Path] = []

    for run_directory in events_directory.iterdir():
        if not run_directory.is_dir():
            continue

        for name in names:
            candidate = run_directory / name

            if candidate.is_file():
                found.append(candidate)
                break

    if not found:
        raise RuntimeError(
            f"No LHE output was found in {events_directory}."
        )

    if len(found) > 1:
        locations = "\n".join(
            f"  {path}"
            for path in found
        )

        raise RuntimeError(
            "More than one LHE output was produced. "
            "FCC Event Runner expects one event sample per run:\n"
            f"{locations}"
        )

    return found[0]


def unpack_lhe(
    source: Path,
    destination: Path,
) -> None:
    destination.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    if source.suffix == ".gz":
        with gzip.open(source, "rb") as compressed:
            with destination.open("wb") as uncompressed:
                shutil.copyfileobj(
                    compressed,
                    uncompressed,
                )
    else:
        shutil.copy2(source, destination)


def create_runtime_seeds(
    madgraph_seed: int | None,
) -> dict[str, int | None]:
    if (
        madgraph_seed is not None
        and 1 <= madgraph_seed <= 899_999_997
    ):
        base_seed = madgraph_seed
    else:
        base_seed = secrets.randbelow(
            899_999_997
        ) + 1

    return {
        "madgraph": madgraph_seed,
        "pythia": base_seed + 1,
        "delphes": base_seed + 2,
    }


def validate_edm4hep_output(
    root_file: Path,
    podio_dump: str,
    log_file: Path,
    environment: dict[str, str],
) -> int:
    if (
        not root_file.is_file()
        or root_file.stat().st_size == 0
    ):
        raise RuntimeError(
            f"The EDM4hep output is missing or empty: {root_file}"
        )

    result = subprocess.run(
        [podio_dump, str(root_file)],
        env=environment,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )

    log_file.write_text(
        result.stdout,
        encoding="utf-8",
    )

    if result.returncode != 0:
        raise RuntimeError(
            f"podio-dump could not read the output. See: {log_file}"
        )

    return parse_podio_event_count(result.stdout)


def preserve_madgraph_metadata(
    process_directory: Path,
    lhe_source: Path,
    log_directory: Path,
) -> None:
    cards_to_copy = [
        (
            process_directory
            / "Cards"
            / "run_card.dat",
            "run_card.dat",
        ),
        (
            process_directory
            / "Cards"
            / "param_card.dat",
            "param_card.dat",
        ),
    ]

    for source, name in cards_to_copy:
        if source.is_file():
            shutil.copy2(source, log_directory / name)

    for banner in lhe_source.parent.glob("*banner.txt"):
        shutil.copy2(
            banner,
            log_directory / banner.name,
        )


def save_lhe_output(
    lhe_file: Path,
    output_file: Path,
) -> None:
    output_file.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    temporary_file = output_file.with_name(
        f".{output_file.name}.tmp"
    )

    with lhe_file.open("rb") as source:
        with gzip.open(
            temporary_file,
            "wb",
        ) as destination:
            shutil.copyfileobj(
                source,
                destination,
            )

    os.replace(temporary_file, output_file)


def build_metadata(
    run_id: str,
    cards: dict[str, Path],
    executables: dict[str, str],
    madgraph_information: dict[str, Any],
    lhe_information: dict[str, Any],
    output_events: int,
    pdf_information: dict[str, Any] | None,
    seeds: dict[str, int | None],
    root_file: Path,
    log_directory: Path,
) -> dict[str, Any]:
    return {
        "run_id": run_id,
        "created_utc": datetime.now(
            timezone.utc
        ).isoformat(),
        "sample": madgraph_information["sample_name"],
        "madgraph": {
            "card": str(cards["madgraph"]),
            "output_directory": madgraph_information[
                "output_directory"
            ],
            "requested_events": madgraph_information["nevents"],
            "beam1_energy_gev": madgraph_information["ebeam1"],
            "beam2_energy_gev": madgraph_information["ebeam2"],
            "matching": matching_description(
                madgraph_information
            ),
        },
        "lhe": lhe_information,
        "edm4hep": {
            "events": output_events,
            "file": str(root_file),
        },
        "pdf": pdf_information,
        "seeds": seeds,
        "cards": {
            name: str(path)
            for name, path in cards.items()
        },
        "executables": executables,
        "logs": str(log_directory),
    }


def create_run_id() -> str:
    return (
        datetime.now(timezone.utc).strftime(
            "%Y%m%d_%H%M%S"
        )
        + f"_{os.getpid()}"
    )


def remove_process_directory(
    process_directory: Path,
    config_directory: Path,
) -> None:
    resolved_process = process_directory.resolve()
    resolved_config = config_directory.resolve()

    try:
        relative_path = resolved_process.relative_to(
            resolved_config
        )
    except ValueError as error:
        raise RuntimeError(
            f"Refusing to remove unsafe path: {resolved_process}"
        ) from error

    if not relative_path.parts:
        raise RuntimeError(
            f"Refusing to remove unsafe path: {resolved_process}"
        )

    shutil.rmtree(resolved_process)